import { promises as fs } from 'node:fs';
import * as nodePath from 'node:path';
import { MANIFEST_FILE_NAME } from './manifest/types';
import { DEFAULT_STALENESS_OPTIONS, type StalenessOptions } from './staleness';

/** Name of the optional project configuration file, read from the project root. */
export const CONFIG_FILE_NAME = 'docsmirror.config.json';

export interface DocsMirrorConfig {
  /** Docs root, relative to the project root. */
  readonly docsRoot: string;
  /** Globs of source files scanned for pointers, relative to the project root. */
  readonly include: readonly string[];
  /** Globs never scanned, and directories never walked. */
  readonly exclude: readonly string[];
  /** Documents treated as entry points by orphan detection. */
  readonly indexes: readonly string[];
  readonly staleness: StalenessOptions;
}

export const DEFAULT_CONFIG: DocsMirrorConfig = {
  docsRoot: 'docs',
  include: ['**/*'],
  exclude: [
    '**/node_modules/**',
    '**/.git/**',
    '**/dist/**',
    '**/out/**',
    '**/build/**',
    '**/coverage/**',
    '**/*.min.*',
    '**/*.lock',
    '**/package-lock.json',
    // Generated by DocsMirror itself, and a copy of the documentation's prose.
    MANIFEST_FILE_NAME,
    // Markdown is documentation, not source: every `#` heading reads as a
    // comment, so scanning it would turn documented examples into pointers.
    '**/*.md',
    '**/*.markdown',
  ],
  indexes: ['index.md', 'README.md'],
  staleness: DEFAULT_STALENESS_OPTIONS,
};

/** A configuration as read from disk: every field optional, staleness deeply so. */
export type PartialConfig = Partial<Omit<DocsMirrorConfig, 'staleness'>> & {
  readonly staleness?: Partial<StalenessOptions>;
};

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((entry) => typeof entry === 'string');
}

/** Reads a parsed JSON value into a partial configuration, ignoring unknown fields. */
export function parseConfig(value: unknown): PartialConfig {
  if (typeof value !== 'object' || value === null) {
    return {};
  }
  const raw = value as Record<string, unknown>;
  const config: {
    docsRoot?: string;
    include?: string[];
    exclude?: string[];
    indexes?: string[];
    staleness?: Partial<StalenessOptions>;
  } = {};

  if (typeof raw['docsRoot'] === 'string') {
    config.docsRoot = raw['docsRoot'];
  }
  if (isStringArray(raw['include'])) {
    config.include = raw['include'];
  }
  if (isStringArray(raw['exclude'])) {
    config.exclude = raw['exclude'];
  }
  if (isStringArray(raw['indexes'])) {
    config.indexes = raw['indexes'];
  }
  const staleness = raw['staleness'];
  if (typeof staleness === 'object' && staleness !== null) {
    const values = staleness as Record<string, unknown>;
    const parsed: Partial<StalenessOptions> = {
      ...(typeof values['agingAfterDays'] === 'number' ? { agingAfterDays: values['agingAfterDays'] } : {}),
      ...(typeof values['staleAfterDays'] === 'number' ? { staleAfterDays: values['staleAfterDays'] } : {}),
    };
    if (Object.keys(parsed).length > 0) {
      config.staleness = parsed;
    }
  }
  return config;
}

/**
 * Layers partial configurations over the defaults, last one winning.
 *
 * `exclude` is the exception: layers add to the default exclusions instead of
 * replacing them, so a project that excludes one folder of its own does not
 * silently start scanning `node_modules`.
 */
export function mergeConfig(...layers: readonly PartialConfig[]): DocsMirrorConfig {
  return layers.reduce<DocsMirrorConfig>(
    (result, layer) => ({
      docsRoot: layer.docsRoot ?? result.docsRoot,
      include: layer.include ?? result.include,
      exclude: [...new Set([...result.exclude, ...(layer.exclude ?? [])])],
      indexes: layer.indexes ?? result.indexes,
      staleness: { ...result.staleness, ...layer.staleness },
    }),
    DEFAULT_CONFIG,
  );
}

export interface LoadedConfig {
  readonly config: DocsMirrorConfig;
  /** Absolute path of the file the configuration came from, when there was one. */
  readonly configPath: string | undefined;
}

/**
 * Loads `docsmirror.config.json` from a project root. A missing file is not an
 * error, the defaults are a working configuration.
 * @docs cli.md#configuration
 */
export async function loadConfig(projectRoot: string, overrides: PartialConfig = {}): Promise<LoadedConfig> {
  const configPath = nodePath.resolve(projectRoot, CONFIG_FILE_NAME);
  let fromFile: PartialConfig = {};
  let found: string | undefined;
  try {
    fromFile = parseConfig(JSON.parse(await fs.readFile(configPath, 'utf8')));
    found = configPath;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw new Error(`Cannot read ${configPath}: ${(error as Error).message}`);
    }
  }
  return { config: mergeConfig(fromFile, overrides), configPath: found };
}
